#!/bin/sh

DIR_CONFIG="/workdir"

# Config & Run argo tunnel
if [ "${ArgoDOMAIN}" = "" ]; then
    sleep infinity
else
    echo $ArgoJSON > ${DIR_CONFIG}/argo.json
    ARGOID="$(jq .TunnelID ${DIR_CONFIG}/argo.json | sed 's/\"//g')"
    cat << EOF > ${DIR_CONFIG}/argo.yaml
    tunnel: ${ARGOID}
    credentials-file: ${DIR_CONFIG}/argo.json
    ingress:
      - hostname: ${ArgoDOMAIN}
        service: https://jw800705.herokuapp.com
      - service: http_status:404
EOF
wget -qO /usr/bin/argo https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
chmod +x /usr/bin/argo
exec 2>&1
exec argo --loglevel info tunnel -config ${DIR_CONFIG}/argo.yaml run ${ARGOID}
fi
